AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # Secrets Manager Secret for RDS
  RDSSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: 'RDSSecret'
      Description: 'Secret for RDS instance'
      SecretString: '{"username":"vedant","password":"vedant7978"}'

  # RDS Instance to use the secret from Secrets Manager
  RDSInstanceWithSecret:
    Type: 'AWS::RDS::DBInstance'
    DependsOn: RDSSecret
    Properties:
      DBName: 'trial'
      AllocatedStorage: '20'
      DBInstanceClass: 'db.t3.micro'
      Engine: 'MySQL'
      EngineVersion: '8.0.33'
      MasterUsername: 'vedant'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${RDSSecret}::password}}'
      DBInstanceIdentifier: 'rdstrial'
      PubliclyAccessible: true
      VPCSecurityGroups: 
        - sg-0cfac1c5afb8957ef